"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { ArrowLeft, Download, Play, Copy, FileText } from "lucide-react";
import { motion } from "framer-motion";
import { toast } from "sonner";
import { CodeMirrorEditor } from "./code-mirror-editor";
import { generateZip } from "@/lib/zip-exporter";

const codeFiles = {
  "App.jsx": `import React, { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <header className="app-header">
        <h1>Welcome to Your App</h1>
        <p>Generated from your design with CodeMorphAI</p>
        <button 
          className="counter-btn"
          onClick={() => setCount(count + 1)}
        >
          Count: {count}
        </button>
      </header>
    </div>
  );
}

export default App;`,
  
  "App.css": `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  min-height: 100vh;
}

.app {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

.app-header {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: white;
  text-align: center;
  padding: 2rem;
}

.app-header h1 {
  font-size: 3rem;
  margin-bottom: 1rem;
  text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
}

.app-header p {
  font-size: 1.2rem;
  margin-bottom: 2rem;
  opacity: 0.9;
}

.counter-btn {
  background: rgba(255, 255, 255, 0.2);
  border: 2px solid rgba(255, 255, 255, 0.3);
  color: white;
  padding: 1rem 2rem;
  font-size: 1.1rem;
  border-radius: 50px;
  cursor: pointer;
  transition: all 0.3s ease;
  backdrop-filter: blur(10px);
}

.counter-btn:hover {
  background: rgba(255, 255, 255, 0.3);
  transform: translateY(-2px);
  box-shadow: 0 10px 20px rgba(0,0,0,0.2);
}

@media (max-width: 768px) {
  .app-header h1 {
    font-size: 2rem;
  }
  
  .app-header p {
    font-size: 1rem;
  }
}`,
  
  "index.html": `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated App - CodeMorphAI</title>
</head>
<body>
  <div id="root"></div>
  <script src="index.js"></script>
</body>
</html>`,
  
  "package.json": `{
  "name": "generated-app",
  "version": "1.0.0",
  "description": "Generated by CodeMorphAI",
  "main": "index.js",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}`
};

export function CodeEditor() {
  const [activeFile, setActiveFile] = useState("App.jsx");
  const [isExporting, setIsExporting] = useState(false);
  const router = useRouter();

  const handleExportZip = async () => {
    setIsExporting(true);
    try {
      await generateZip(codeFiles);
      toast.success("Code exported successfully!");
    } catch (error) {
      toast.error("Failed to export code");
    } finally {
      setIsExporting(false);
    }
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(codeFiles[activeFile as keyof typeof codeFiles]);
    toast.success("Code copied to clipboard!");
  };

  const getFileLanguage = (filename: string) => {
    if (filename.endsWith('.jsx') || filename.endsWith('.js')) return 'javascript';
    if (filename.endsWith('.css')) return 'css';
    if (filename.endsWith('.html')) return 'html';
    if (filename.endsWith('.json')) return 'json';
    return 'javascript';
  };

  return (
    <div className="h-screen bg-background flex flex-col">
      {/* Header */}
      <motion.header
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        className="h-16 border-b border-border bg-card/50 backdrop-blur-sm flex items-center justify-between px-6"
      >
        <div className="flex items-center space-x-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => router.push('/dashboard')}
          >
            <ArrowLeft className="w-4 h-4" />
          </Button>
          <div>
            <h1 className="text-lg font-semibold">Code Editor</h1>
            <p className="text-sm text-muted-foreground">Generated from your design</p>
          </div>
        </div>
        
        <div className="flex items-center space-x-3">
          <Button variant="outline" onClick={handleCopyCode}>
            <Copy className="w-4 h-4 mr-2" />
            Copy Code
          </Button>
          <Button variant="outline">
            <Play className="w-4 h-4 mr-2" />
            Preview
          </Button>
          <Button 
            onClick={handleExportZip}
            disabled={isExporting}
            className="bg-primary hover:bg-primary/90 text-primary-foreground"
          >
            {isExporting ? (
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                className="w-4 h-4 border-2 border-primary-foreground border-t-transparent rounded-full mr-2"
              />
            ) : (
              <Download className="w-4 h-4 mr-2" />
            )}
            {isExporting ? "Exporting..." : "Export ZIP"}
          </Button>
        </div>
      </motion.header>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* File Explorer */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.2 }}
          className="w-64 bg-card border-r border-border"
        >
          <div className="p-4 border-b border-border">
            <h2 className="font-semibold text-sm">Generated Files</h2>
          </div>
          <ScrollArea className="h-full">
            <div className="p-2 space-y-1">
              {Object.keys(codeFiles).map((filename) => (
                <Button
                  key={filename}
                  variant={activeFile === filename ? "secondary" : "ghost"}
                  className="w-full justify-start h-8 px-3"
                  onClick={() => setActiveFile(filename)}
                >
                  <FileText className="w-4 h-4 mr-2" />
                  <span className="font-mono text-xs">{filename}</span>
                </Button>
              ))}
            </div>
          </ScrollArea>
        </motion.div>

        {/* Code Editor */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="flex-1 flex flex-col"
        >
          <div className="h-12 bg-card border-b border-border flex items-center px-4">
            <span className="font-mono text-sm font-medium">{activeFile}</span>
          </div>
          
          <div className="flex-1 bg-background">
            <CodeMirrorEditor
              value={codeFiles[activeFile as keyof typeof codeFiles]}
              language={getFileLanguage(activeFile)}
              onChange={(value) => {
                // Handle code changes
                console.log('Code changed:', value);
              }}
            />
          </div>
        </motion.div>

        {/* Preview Panel */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ delay: 0.4 }}
          className="w-96 bg-card border-l border-border"
        >
          <div className="p-4 border-b border-border">
            <h2 className="font-semibold text-sm">Live Preview</h2>
          </div>
          <div className="p-4 h-full">
            <Card className="h-full">
              <CardHeader>
                <CardTitle className="text-sm">Output Preview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-gradient-to-br from-blue-400 to-purple-600 rounded-lg p-8 text-white text-center">
                  <h1 className="text-2xl font-bold mb-4">Welcome to Your App</h1>
                  <p className="mb-6">Generated from your design with CodeMorphAI</p>
                  <button className="bg-white/20 backdrop-blur-sm border border-white/30 text-white px-6 py-3 rounded-full hover:bg-white/30 transition-all">
                    Count: 0
                  </button>
                </div>
              </CardContent>
            </Card>
          </div>
        </motion.div>
      </div>
    </div>
  );
}